### ISSUE TITLE
Testing: VIAF data type

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/ValueSuggest#11]
The [oclc_viaf](https://github.com/omeka-s-modules/ValueSuggest/tree/oclc_viaf) branch adds the VIAF data type. Add a resource template and assign the "Value Suggest: OCLC: The Virtual International Authority File (VIAF)" data type to a property. Add an item, switch to the template, and test whether the property autosuggests options. When selected the value should include a URI.

**Comment by mebrett** [comment]
Values include URIs, they populate fine, and I couldn't break the module at all on this branch.
