### ISSUE TITLE
Suggest does not work for Item Sets

### ISSUE THREAD

**Issue by mebrett** [omeka-s-modules/ValueSuggest#12]
Not sure if this is a bug or expected behavior.

Because we can apply Resource Templates to Item Sets as well as Items, users might apply a resource template with Value Suggest to an item set. When this happens, they can type in whatever they want but the suggest part doesn't work, and the value isn't saved.

![screen shot 2017-06-09 at 11 44 58 am](https://user-images.githubusercontent.com/2314070/26983270-356c1294-4d09-11e7-9b30-391c1c1fc4b4.png)

![screen shot 2017-06-09 at 11 45 43 am](https://user-images.githubusercontent.com/2314070/26983271-357051ec-4d09-11e7-880a-01dfe241abb5.png)

**Comment by zerocrates** [comment]
Definitely a bug.
