### ISSUE TITLE
Should source names/initials be translated?

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/ValueSuggest#15]
Currently, in the datatype list, "LC", "Getty", and "OCLC" are included in the translatable strings. It seems like these would be confusing to translators, and that as names of services maybe they shouldn't be translated at all.

**Comment by patrickmj** [comment]
@jimsafley @kimisgold @zerocrates  Any thoughts on this question?

**Comment by jimsafley** [comment]
They should not be translated.

**Comment by zerocrates** [comment]
Omitting them is probably a good call.

**Comment by patrickmj** [comment]
So, how do we do that? For example, in the file for LC:Children's Subjects the label comes from
https://github.com/omeka-s-modules/ValueSuggest/blob/master/src/DataType/Lc/Childrenssubjects.php#L24
```
        return 'LC: Children\'s Subject Headings'; // @translate
```

So, how to split it apart?

Does some `sprintf` trickery work here (maybe after getting the translator from the ServiceManager?), or are forced into putting the string together in separate lines, like

```php
$label = 'LC: ';
$label .= 'Children\'s Subject Headings'; // @translate
return $label;
```

**Comment by jimsafley** [comment]
Good point. Since Zend auto-translates the labels when generating the select element's markup I don't see a way for us to to translate only part of the string. In this case I think we need to trust translators to do the right thing and not translate proper nouns.

**Comment by patrickmj** [comment]
Tangential note, I think we hit the same problem with "Default --" in the language selector dropdown.

**Comment by jimsafley** [comment]
"Default—" is going away in a forthcoming commit.

**Comment by patrickmj** [comment]
Problem solved!
