### ISSUE TITLE
Suggest not working for editor or author users

### ISSUE THREAD

**Issue by mebrett** [omeka-s-modules/ValueSuggest#20]
Suggest works fine for Global and Site Admins. For editor and author users, the cursor briefly becomes a spinning wheel but nothing is suggested. Per [this post on the forum](https://forum.omeka.org/t/value-suggest-only-working-for-global-admin/7250)

**Comment by jimsafley** [comment]
Fixed in 8ebc66ddbc07e1476588a8fc1f6139e201bc127a
