### ISSUE TITLE
Adding support for RDA value vocabularies

### ISSUE THREAD

**Issue by IhreGeschichte** [omeka-s-modules/ValueSuggest#23]
Extending the ValueSuggest module to the RDA value vocabularies <http://www.rdaregistry.info/termList/> would be a great leap towards semantic web AND internationalization (i.e. the vocabularies are allready translated to a couple of major languages).

**Comment by jimsafley** [comment]
ValueSuggest normally depends on third-party vocabulary services to provide an endpoint that accepts queries for suggestions. It doesn't look like RDA provides an endpoint, but it does publish structured data about each vocabulary, and the vocabularies may be small enough to justify fetching the entire data set and parsing out the suggestions.

As for internationalization, this module does not explicitly handle it, and perhaps it should. I wonder if the existing services handle it via a locale parameter or as a side-effect of a query. At any rate, perhaps the module could try to suggest only those values that match the configured locale of the Omeka installation.

**Comment by IhreGeschichte** [comment]
On the single vocabulary pages, there is a link to an api like for example http://api.metadataregistry.org/vocabularies/437. Perhaps this API could serve as "an endpoint that accepts queries for suggestions"?

"At  any rate, perhaps the module could try to suggest only those values  that match the configured locale of the Omeka installation." I think this would be a great feature.

**Comment by jimsafley** [comment]
I saw those "API" links, but the Open Metadata Registry's API seems to be undocumented. Now that I look closer, the Registry does provide a [SPARQL endpoint](http://metadataregistry.org/endpoint.php) that could be useful when querying large vocabularies. However, the largest vocabulary registered by RDA is 107 concepts; most are under 20. It seems to me that ValueSuggest's current suggestion behavior is not ideal for small data sets, but it could possibly be modified to accommodate them. (I first proposed it in [this issue](https://github.com/omeka-s-modules/ValueSuggest/issues/1).) I'll experiment a bit.

**Comment by IhreGeschichte** [comment]
The drop-down menus work just fine for these small vocabularies. By changing the 'prefabel' and 'definition' values in src/Suggester/Rda/RdaSuggestAll.php to one's locale one even gets the vocabularies' translations. One last thing: Would it be much work to make ValueSuggest sort these translated suggestions alphabetically?

**Comment by jimsafley** [comment]
Good idea. It's fine to sort the RDA query results since they're not already sorted in any logical order, as far as I can tell. Other queries, such as those made to the LC endpoints, are sorted by relevance so an alphabetical sorting would be inappropriate.
