### ISSUE TITLE
Testing: New behavior for small vocabularies

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/ValueSuggest#24]
The [valuesuggestall branch](https://github.com/omeka-s-modules/ValueSuggest/tree/valuesuggestall) adds a second suggestion behavior designed for small vocabularies. Whereas the default behavior is to provide a list of suggestions after the user types a minimum of three characters, this new behavior provides the suggestions immediately after the input has focus.

Internally, the typical strategy is to query a third-party service against a search endpoint and return back a limited result set every time a user enters or removes a character. This re-querying is not optimal for small vocabularies. This branch enables a new strategy that fetches and returns an entire vocabulary before any character is entered, and does not perform subsequent queries.

Test a few of the new RDA data types, which use the new behavior. The only difference you should see is that the suggestions appear immediately after the input has focus. Verify that all other behavior is the same.

**Comment by mebrett** [comment]
I'm playing with as many of the vocabularies as I can. So far, when I assign http://www.rdaregistry.info/termList/MusNotation/ to a property, the terms never load on item add/edit. I just get a hangup spinning icon under the cursor.

**Comment by mebrett** [comment]
the fix you made has solved the hangup issue, and everything is now working as expected. Sometimes there's a second or two lag before the terms load, but it's short.

**Comment by HistArchivist** [comment]
The hangup issue seems to be back with 1.4.0.

**Comment by jimsafley** [comment]
Thanks for the note. Although the effects are similar, I don't think this is the same issue. See https://github.com/omeka-s-modules/ValueSuggest/issues/33
