### ISSUE TITLE
Testing: PeriodO vocabulary

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/ValueSuggest#26]
The [periodo branch](https://github.com/omeka-s-modules/ValueSuggest/tree/periodo) introduces the [PeriodO](http://perio.do/en/) vocabulary, a public domain gazetteer of scholarly definitions of historical, art-historical, and archaeological periods. It should work like any other vocabulary.

**Comment by mebrett** [comment]
Works perfectly.

**Comment by jimsafley** [comment]
Resolved in 6fccf37c44243112c833ba991b3e139d6fdfff4d
