### ISSUE TITLE
Testing: Tesauros vocabulary

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/ValueSuggest#28]
The [tesauros branch](https://github.com/omeka-s-modules/ValueSuggest/tree/tesauros) introduces the [Tesauros](http://tesauros.mecd.es/tesauros/tesauros) vocabularies. Each should work like any other vocabulary.

**Comment by jimsafley** [comment]
The branch also includes a few [UNESCO](http://skos.um.es/vocabularios/index.php) vocabularies that should be tested.

**Comment by mebrett** [comment]
It is suggesting terms for both the Tesauros and UNESCO vocabs.
