### ISSUE TITLE
Homosaurus Label

### ISSUE THREAD

**Issue by brimwats** [omeka-s-modules/ValueSuggest#34]
Currently, the plugin displays: Homosaurus: the International Thesaurus of Lesbian, Gay, Bisexual and Transgender Index Terms that is currently used by https://www.digitaltransgenderarchive.net.

the DTA does not use homosaurus v2. It will in the future. Homosaurus has been upgraded to v2 (and was upgraded here as well).

The correct name would be: 

Homosaurus:   an international LGBTQ Linked Data Vocabulary http://homosaurus.org

(I am on the homosaurus board and happy to answer any questions!)

**Comment by jimsafley** [comment]
Thank you for the correction. It will be updated in the next release.

**Comment by brimwats** [comment]
Thanks! I saw the correction! Appreciated.


B


________________________________
