### ISSUE TITLE
University of Barcelona Thesaurus (THUB)

### ISSUE THREAD

**Issue by xavivalenti** [omeka-s-modules/ValueSuggest#35]
Hi there!

Could you please add support for [Thesaurus de la Universitat de Barcelona (THUB)](https://crai.ub.edu/ca/recursos-d-informacio/thub).

There is a SPARQL endpoint at this URL: https://data.coeli.cat/thub

Thanks in advance!
Xavi

**Comment by jimsafley** [comment]
Thanks for the suggestion. The SPARQL endpoint is currently out of service.

**Comment by jimsafley** [comment]
Endpoint successfully accessed on May 20, 2022. https://data.coeli.cat/thub

**Comment by xavivalenti** [comment]
Hi,
It seems that the certificate is already working now. Could you please try again?
Regards,

**Comment by jimsafley** [comment]
Added in the [newest release](https://github.com/omeka-s-modules/ValueSuggest/releases/tag/v1.12.0).
