### ISSUE TITLE
Convert to litteral

### ISSUE THREAD

**Issue by Daniel-KM** [omeka-s-modules/ValueSuggest#38]
There is a x to remove the uri on a value suggest and the comment says it converts the datatype to literal : https://github.com/omeka-s-modules/ValueSuggest/blob/77f45caab5fac41ff794c449297bd1e59e73e65f/asset/js/valuesuggest.js#L72
But the datatype stays valuesuggest. So is it the comment that is not up-to-date or the feature that is not implemented ?

**Comment by Daniel-KM** [comment]
It's feature to keep anyway.

**Comment by jimsafley** [comment]
It should read:

> Remove the @id from URI type and transform it into "Literal" type

Note the scare quotes. It stays `valuesuggest` but it _appears_ to be a literal, since there is no longer an `@id`. I see no reason to actually transform the value to a `literal` data type.
