### ISSUE TITLE
Adding support for "Thésaurus de la désignation des objets mobiliers"

### ISSUE THREAD

**Issue by pprw** [omeka-s-modules/ValueSuggest#45]
http://data.culture.fr/thesaurus/page/ark:/67717/T69

It is available in [RDF/XML](data.culture.fr/thesaurus/data/ark:/67717/T69?includeSchemes=true), [Notation3](data.culture.fr/thesaurus/data/ark:/67717/T69?includeSchemes=true&format=N3) and [Turtle](data.culture.fr/thesaurus/data/ark:/67717/T69?includeSchemes=true&format=TURTLE)

There is a [SPARQL Endpoint](http://data.culture.fr/thesaurus/sparql).

**Comment by jimsafley** [comment]
Added via the "Les vocabulaires du Ministère de la Culture et de la Communication" collection of suggesters.
