### ISSUE TITLE
Add the possibility to override ValueSuggest quickly 

### ISSUE THREAD

**Issue by pprw** [omeka-s-modules/ValueSuggest#46]
Let's say I use ValueSuggest for GeoName. Time to time, I need to enter a specific place by hand because I cannot find a correct result in GeoName. For each time, I have to modify the template settings, to remove GeoName for the field, make the change, and restore the template original state. 

With GeoName, you need to indicate an URL so you cannot simply modify the name of the place (or you will be not able to save the item).

I would be very useful to have a button which override ValueSuggest for a specific field and allow plain text.

**Comment by jimsafley** [comment]
You should be able to save _any_ text into a ValueSuggest-enabled value, not just suggested text. If you can't, then something is wrong.
