### ISSUE TITLE
Testing: RightsStatements.org suggester

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/ValueSuggest#54]
The [rights-statements branch](https://github.com/omeka-s-modules/ValueSuggest/compare/rights-statements) introduces the RightsStatements.org suggester. To test this, edit any resource template and, on any property, set the "Data type" to "RightsStatements.org." Set the changes and save the form. Then, add an item, select the resource template, and, on the property you edited, click in the input. A dropdown of available rights statements should appear. Hovering over the items should bring up a tooltip containing information about the statement. Select any rights statement and save the form. You should see a link to the statement you selected.

**Comment by georgiawebgurl** [comment]
Chrome Version 88.0.4324.150 (Official Build) (64-bit) 
This works as stated (nifty!)

One general comment:
In the dropdown for selecting the Data type, the verbiage,  "RightsStatements.org: Standardized rights statements for online cultural heritage" - I think "Standardized rights statements" would be fine. 

I will test in Edge,

**Comment by sharonmleon** [comment]
Let’s leave this open until the testing is complete across browsers.

**Comment by jimsafley** [comment]
> In the dropdown for selecting the Data type, the verbiage, "RightsStatements.org: Standardized rights statements for online cultural heritage" - I think "Standardized rights statements" would be fine.

RightsStatements.org publishes rights statements that are specifically for cultural heritage institutions. It's important to convey that in the name.

**Comment by georgiawebgurl** [comment]
> Let’s leave this open until the testing is complete across browsers.
> 
> Then, the next step will be to update the documentation, and push that when Jim does the release.

Thanks - Sorry, I didn't notice I clicked close.

**Comment by georgiawebgurl** [comment]
Firefox 85.0.2 (64-bit) - Works as stated
Version 88.0.705.63 (Official build) (64-bit) - Works as stated
Android 11 (Samsung Galaxy S20) - Works as stated

Unfortunately, I have no IOS devices and Safari for Windows is no longer supported. 
Let me know if there is anything else I should test.

**Comment by jimsafley** [comment]
Thanks. That's more than enough.
