### ISSUE TITLE
UnescoThesaurus

### ISSUE THREAD

**Issue by luis575497** [omeka-s-modules/ValueSuggest#58]
Hello, I have the version 3.0.2 of Omeka S installed and the version of ValueSuggest 1.9.0, and when I put the Unesco thesaurus as a vocabulary, I do not see the correct results for the Thesaurus in Spanish for example, if I look for architecture,
![Captura](https://user-images.githubusercontent.com/46435934/146244967-d95532a7-3c28-4e6c-a3fd-a8534ffb378c.PNG)
 this does not appear I finish that if it is in the thesaurus
![Captura1](https://user-images.githubusercontent.com/46435934/146244988-3ab9f372-dcdb-474a-9c51-1e0dbfa8d16d.PNG)
How could I solve this problem

**Comment by jimsafley** [comment]
The Unesco suggester queries the provided [SPARQL endpoint](https://skos.um.es/sparql/) for suggestions. While the resulting labels are identical, they all reference unique resources, which you can differentiate by hovering overs the options for a tooltip.
