### ISSUE TITLE
Labels in other language

### ISSUE THREAD

**Issue by coret** [omeka-s-modules/ValueSuggest#63]
Is it possible to specify the language for the returned label (and property) of a valuesuggest field? Several vocabularies, like the Getty AAT are multi-langual, and now only seem to return English labels (although my Omeka S wide language setting is `nl`).

Is do see language is a parameter in the suggester:
https://github.com/omeka-s-modules/ValueSuggest/blob/7428a29791a6acb9ecc5f750a0c5724c5561d545/src/Controller/IndexController.php#L58

But when I click the "globe" icon in the Item edit page, nothing seems to happen? Besides a change in icon and alt-text (Remove language). For non-valuesuggest fields I do get a pull-down of my defined languages, like `nl`, `en`, `de`.

![image](https://user-images.githubusercontent.com/101820/167385697-a58c381e-33a8-4caf-9bac-582b708a30c7.png)

Additionally, I'd really like to specify the default language (`nl`) for the valuesuggest field in the Resource template.

**Comment by jimsafley** [comment]
Thanks for pointing this out. It should be fixed in the [next release](https://github.com/omeka-s-modules/ValueSuggest/releases/tag/v1.11.0).

**Comment by coret** [comment]
@jimsafley I've tested 1.11.0. You can now indeed select a language.

**But** the defined vocabulary isn't searched. I've looked at the [changed files](https://github.com/omeka-s-modules/ValueSuggest/commit/de7f32f1b8cf138be6a8a941c937b58bcfb785e1) but this is only language files, so no clue why the search is broken now.

**Comment by coret** [comment]
I've tested in a Incognito windows of Chrome to avoid caching issues.
I defined 2 properties with valuesuggest, one being the AAT and the other Geonames.

I have an environment with ValueSuggest 1.10.0 and there is see, after typing some characters, calls to admin/value-suggest/proxy?query=****&lang=&type=valuesuggest%3Agetty%3Aaat. In the environment with ValueSuggest 1.11.0 I don't see any of the proxy calls being made at all. No Javascript/console errors of log entries...

**Comment by jimsafley** [comment]
What Omeka S version are you using? On the modules page, does Value Suggest say it's at version 1.11.0?

**Comment by coret** [comment]
In both my Omeka environments I run 3.2.0. On the modules page I do see resp. Value Suggest version 1.10.0 and 1.11.0.

One difference I've spotted: in the 1.10.0 version the value suggest input field has class `valuesuggest-input`. The 1.11.0 version shows the same field has `wikidata-input` as class?? So https://github.com/omeka-s-modules/ValueSuggest/blob/master/asset/js/valuesuggest.js#L5 would not get a value in the 1.11.0 form.

**Comment by coret** [comment]
Ah, I disabled the [Wikidata](https://github.com/nishad/omeka-s-wikidata) module  (version 1.3.0) and the ValueSuggest 1.11.0 now works! 

I don't quit understand, because I had this module active with a working ValueSuggest 1.10.0...
