### ISSUE TITLE
Feature Request: Adding support for ORCID

### ISSUE THREAD

**Issue by m-art-in** [omeka-s-modules/ValueSuggest#68]
Is there a plan to integrate [ORCID](https://orcid.org/) as well? 

Unfortunately, ORCID's API can only be used with a key. This could be stored in config.json

**Comment by jimsafley** [comment]
We have no plans to integrate ORCID. How do you see this being used?

**Comment by m-art-in** [comment]
Orcid is primarily used in the librarian field to uniquely identify authors. Almost every library catalog (opac etc.) tags the authors with this ID. 

I have started to extend the ValueSuggest module myself. Unfortunately Orcid requires an api key.

**Comment by m-art-in** [comment]
Update:
I just found there is a public sandbox api which can be used without a key.
[Documentation](https://info.orcid.org/documentation/api-tutorials/api-tutorial-searching-the-orcid-registry/#easy-faq-2703)
Example query could be: https://pub.sandbox.orcid.org/v3.0/search/?q=family-name:Sanchez&start=4&rows=6

I'll try this for testing
