### ISSUE TITLE
Testing: Suggest Omeka values

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/ValueSuggest#71]
The [omeka-suggesters](https://github.com/omeka-s-modules/ValueSuggest/compare/omeka-suggesters) branch adds three data types that suggest values that already exist in the working Omeka installation:

- **Omeka: Property**: suggest values using the current value's property
- **Omeka: Property / Resource template**: suggest values using the current value's property and current resource's template
- **Omeka: Property / Resource class**: suggest values using the current value's property and current resource's class

To test this, it's best to have a lot of richly described items. You could use the [Omeka S Item Importer](https://github.com/omeka-s-modules/Osii) module to import from any number of [Omeka S installations](https://omeka.org/s/directory/). When editing a resource template, add each new data type to properties that are often used to categorically describe resources, such as `dcterms:type` or `dcterms:subject`. Then, add an item, select the resource template you edited, and start typing values that you know exist for that property/template/class combination. It should work for both Text and URI types. It should respect the current language.

**Comment by allanaaa** [comment]
I'm not getting anything. After the third character is typed, my cursor changes to a spinning wheel for a second (and for every character after), but nothing is being suggested. 
![vs](https://user-images.githubusercontent.com/28012148/224076695-ccfc5e66-f0c2-4892-9062-fb9c741d7c07.gif)

**Comment by allanaaa** [comment]
Yep. "edinburgh" and "paisley" should get it going for publishers, "bunyan" for creator. 

All I've got is "wrong event specified: touchleave DomEvent.Pointer.js:36:10" for errors.

**Comment by jimsafley** [comment]
What data type of the three are you using for that property?

**Comment by allanaaa** [comment]
I set all of them to "Omeka property" for the widest range. I have done some template and class labelling of my items but I haven't used those data types yet.

**Comment by allanaaa** [comment]
Hrm, it's working now! And it's positively beautiful. 
![pai](https://user-images.githubusercontent.com/28012148/224087023-221844a4-9709-4d22-aaa6-b7b386e7d155.PNG)

I did go and turn off a bunch of other modules as part of the troubleshooting, not clear if that was part of it or if it just needed time to index behind the scenes?

**Comment by jimsafley** [comment]
It is strange. The only reason it _should_ behave that way is if you're logged in as an author and the source item is set to private. Otherwise, I'm at a loss. There's no indexing. Try activating modules one at a time to see if one breaks this feature.

**Comment by allanaaa** [comment]
All modules are active and everything seems to be fine.
