### ISSUE TITLE
Add new RBMS LC vocab

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-modules/ValueSuggest#76]
New-to-us vocabulary: https://id.loc.gov/vocabulary/rbmscv.html

I ran through the list and didn't see anything else to add from LC or most else we currently support. Although I didn't look to closely at things in other languages. RDA is a separate issue.

I wonder: would there be a function to support translation forks of things like RightsStatements? https://rightsstatements.org/en/documentation/translations.html

**Comment by jimsafley** [comment]
Added in 23413594104ef192393949245d348c6e9f3e1e17
