### ISSUE TITLE
Test module

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/ValueSuggest#8]
This module adds a long list of "LC" and "Getty" data types to the resource template add/edit interface. Test this module the same as you would test any resource template data type: go add a template and set a data type to any property, then go add an item and select the template. The property you chose should appear as a text input. Enter any text and wait for the autosuggest select menu. You can hover over some of these selections to get clarifications. Select one and save the item. Test a sampling of "LC" and "Getty" data types.

**Comment by jimsafley** [comment]
I also should note that, once selected, a box containing a URL should appear under the value. This link resolves to a web page that represents the value you selected. You can remove the URL box by clicking the "x". Saving a value with the URL should make it a URI type value. Saving a value without the URL should make it a literal value.

**Comment by mebrett** [comment]
Both Jannelle and I played around with the module. It works as described an we were unable to break it.
