### ISSUE TITLE
Tesauros not loading | SPARQL end point has changed

### ISSUE THREAD

**Issue by saponidas** [omeka-s-modules/ValueSuggest#83]
"Tesauros del patrimonio cultural de España" are not loading for few days ago.

While checking on this I saw the the SPARQL endpoint has changed 
from http://tesauros.mecd.es/tesauros/sparql
to http://tesauros.cultura.gob.es/tesauros/sparql

I made a few tests, and solved it by simply updating the URLs in the module files.

**Find the files**

```
grep -Rnw 'path/to/modules/ValueSuggest' -e 'tesauros.mecd.es'
```

- path/to/modules/ValueSuggest/README.md
- path/to/ValueSuggest/src/Suggester/Tesauros/Sparql.php
- path/to/modules/ValueSuggest/src/Service/TesaurosDataTypeFactory.php

**sed to change the URLs**  
First, backup the files and launch the command **without** ``` -i ``` to see the changes before apply them. If all seems correct, launch the commands with ``` -i ```

```
cd  path/to/ValueSuggest
sed -i "s/tesauros.mecd.es/tesauros.cultura.gob.es/g"  ./src/Suggester/Tesauros/Sparql.php
sed -i "s/tesauros.mecd.es/tesauros.cultura.gob.es/g"  ./src/Service/TesaurosDataTypeFactory.php
```

I don't know if there is something they can do to fix it on their side. The old end point is redirected to the new one, but probably is wild redirection or some parameters are missing.

I will send them an email with the link to this issue,  Maybe you can contact them to further investigation:
Site: http://tesauros.cultura.gob.es/tesauros/linked-open-data
Email: tesauros.museos@mcu.es

Best,

**Comment by jimsafley** [comment]
Thank you for bringing this to our attention. I've updated the endpoint and schemes. The fix will be in the next release.

**Comment by saponidas** [comment]
Hi again, they have changed the endpoint again, and it is not working. Neither the old endpoint (http://tesauros.mecd.es/tesauros/sparql), the one in the fix (http://tesauros.cultura.gob.es/tesauros/sparql), or the one they indicate now (https://tesauros.cultura.gob.es:443/tesauros/sparql   note that link goes to the URL without :443  -->  https://tesauros.cultura.gob.es/tesauros/sparql )

I wrote them several emails, not response.
It is strange, the end point seems to work (eg. [link to 5 results](https://tesauros.cultura.gob.es/tesauros/sparql?query=PREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0D%0APREFIX+foaf%3A+%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2F%3E%0D%0APREFIX+dct%3A+%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Fterms%2F%3E%0D%0APREFIX+owl%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%0D%0APREFIX+xsd%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0D%0APREFIX+rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0D%0APREFIX+tes%3A+%3Chttp%3A%2F%2Ftesauros.mecd.es%2Ftesauros%2Fvocab%23%3E%0D%0APREFIX+skos%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23%3E%0D%0ASELECT+*+%0D%0AWHERE+%7B%0D%0A++%3Fs+skos%3AprefLabel+%3Fo%0D%0A%7D%0D%0ALIMIT+5&format=text%2Fhtml)  ), but it is not connecting.


The error I am getting from the console:
```
Laminas\Http\Client\Adapter\Exception\RuntimeException
Unable to enable crypto on TCP connection tesauros.cultura.gob.es: make sure the "sslcafile" or "sslcapath" option are properly set for the environment.

Details:

ErrorException: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:0A000086:SSL routines::certificate verify failed in "/path/to/public_html/public_html/vendor/laminas/laminas-http/src/Client/Adapter/Socket.php:397
Stack trace:
#0 [internal function]: Laminas\Stdlib\ErrorHandler::addError()
#1 "/path/to/public_html/public_html/vendor/laminas/laminas-http/src/Client/Adapter/Socket.php(397): stream_socket_enable_crypto()
#2 "/path/to/public_html/public_html/vendor/laminas/laminas-http/src/Client/Adapter/Socket.php(355): Laminas\Http\Client\Adapter\Socket->enableCryptoTransport()
#3 "/path/to/public_html/public_html/vendor/laminas/laminas-http/src/Client.php(1465): Laminas\Http\Client\Adapter\Socket->connect()
#4 "/path/to/public_html/public_html/vendor/laminas/laminas-http/src/Client.php(965): Laminas\Http\Client->doRequest()
#5 "/path/to/public_html/public_html/modules/ValueSuggest/src/Suggester/Tesauros/Sparql.php(58): Laminas\Http\Client->send()
#6 "/path/to/public_html/public_html/modules/ValueSuggest/src/Controller/IndexController.php(62): ValueSuggest\Suggester\Tesauros\Sparql->getSuggestions()
#7 "/path/to/public_html/public_html/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(71): ValueSuggest\Controller\IndexController->proxyAction()
#8 "/path/to/public_html/public_html/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\Controller\AbstractActionController->onDispatch()
#9 "/path/to/public_html/public_html/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners()
#10 "/path/to/public_html/public_html/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(97): Laminas\EventManager\EventManager->triggerEventUntil()
#11 "/path/to/public_html/public_html/vendor/laminas/laminas-mvc/src/DispatchListener.php(132): Laminas\Mvc\Controller\AbstractController->dispatch()
#12 "/path/to/public_html/public_html/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\DispatchListener->onDispatch()
#13 "/path/to/public_html/public_html/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners()
#14 "/path/to/public_html/public_html/vendor/laminas/laminas-mvc/src/Application.php(325): Laminas\EventManager\EventManager->triggerEventUntil()
#15 "/path/to/public_html/public_html/index.php(21): Laminas\Mvc\Application->run()
#16 {main}
```

I will update the issue if they reply.

Best,
