### ISSUE TITLE
idref's  vocabularies not working

### ISSUE THREAD

**Issue by pprw** [omeka-s-modules/ValueSuggest#84]
There are no auto-suggest data for idref's vocabularies (other vocabularies work fine) in latest Omeka S & ValueSuggest.

**Comment by jimsafley** [comment]
The module does successfully retrieve suggestions from IdRef, but PHP is emitting a deprecation warning that invalidates the returned JSON:

```
Deprecated:  Creation of dynamic property Laminas\Http\Header\SetCookie::$type is deprecated in /var/www/html/omeka-s/vendor/laminas/laminas-http/src/Header/SetCookie.php on line 267
```

Omeka is using an older version of [laminas-http](https://github.com/laminas/laminas-http). Upgrading to a newer version will fix this. Until then, you could turn off deprecation warnings or add the following to `ValueSuggest\Suggester\IdRef\IdRefSuggestAll::getSuggestions()`:

```php
error_reporting(error_reporting() ^ E_DEPRECATED);
```

It is odd that the IdRef suggester raises this warning but other suggesters don't. They all use the same HTTP client. The IdRef server probably returns a cookie for whatever reason.

**Comment by pprw** [comment]
Thanks Jim.

ABES (which provides idRef) changes this and we can now retrieve suggestions without issue.
