### ISSUE TITLE
Add VIAF

### ISSUE THREAD

**Issue by sharonmleon** [omeka-s-modules/ValueSuggest#9]
Can we add VIAF to the list of authority files?
https://datahub.io/dataset/viaf

**Comment by jimsafley** [comment]
After a quick look there doesn't seem to be an endpoint to query. This means we'd need to a) download the dataset and create our own endpoint or b) reverse engineer the web search and scrape the screen during runtime, neither of which are feasible, to be honest. I'll look into this more.

**Comment by jimsafley** [comment]
Yes, it appears we can add VIAF to the list. I've found the [suggest endpoint](http://www.viaf.org/viaf/AutoSuggest?query=austen) ([demo](https://platform.worldcat.org/api-explorer/apis/VIAF/AuthorityCluster/AutoSuggest)).

**Comment by sharonmleon** [comment]
Excellent.

**Comment by jimsafley** [comment]
A WIP in the [oclc_viaf](https://github.com/omeka-s-modules/ValueSuggest/tree/oclc_viaf) branch.

**Comment by jimsafley** [comment]
Added in 4359b484e56e81dadf474209d057d6a30a034e9e
